runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3.7

service: course-discussion-service

env_variables:
  REDISHOST: '10.234.140.171'
  REDISPORT: '6379'

beta_settings:
  cloud_sql_instances: upbeat-stratum-310102:us-central1:cloudmysql

network:
  name: default